export const MODIFY_INGREDIENT = "MODIFY_INGREDIENT";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGERDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGERDIENTS_FAIL";
export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";

export const SUBMIT_ORDER_START = "SUBMIT_ORDER_START";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_FAIL = "SUBMIT_ORDER_FAIL";
export const INIT_PURCHASE = "INIT_PURCHASE";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START";
export const AUTH_SET_REDIRECT_PATH = "AUTH_SET_REDIRECT_PATH";
export const AUTH_CHECKSTATE = "AUTH_CHECKSTATE";
export const AUTH_CHECKSTATE_DONE = "AUTH_CHECKSTATE_DONE";
export const AUTH_CHECK_EXPIRE_TOKEN = "AUTH_CHECK_EXPIRE_TOKEN";
