export const MODIFY_INGREDIENT = "MODIFY_INGREDIENT";
export const FETCH_INGREDIENTS_SUCCESS = "FETCH_INGERDIENTS_SUCCESS";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGERDIENTS_FAIL";

export const SUBMIT_ORDER_START = "SUBMIT_ORDER_START";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_FAIL = "SUBMIT_ORDER_FAIL";
export const INIT_PURCHASE = "INIT_PURCHASE";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
